[build-system]
requires = ["setuptools>=70", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "package-deploy"
version = "0.1.0"
description = "Modern Python Package Deployment Tool"
requires-python = ">=3.8"
dependencies = [
    "toml",
    "tomlkit",
    "virtualenv",
    "build",
    "twine",
    "Cython"
]

[tool.setuptools]
package-dir = {"" = "src"}
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]