[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "package-deploy"
version = "0.1.0"
description = "Modern Python Package Deployment Tool"
requires-python = ">=3.8"
dependencies = [
    "toml",
    "tomlkit",
    "build",
    "twine",
]

[project.optional-dependencies]
cython = ["Cython>=0.29.0"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]