[build-system]
requires = ["setuptools>=70"]
build-backend = "setuptools.build_meta"

[project]
name = "package-deploy"
version = "0.1.4"
description = "Modern Python Package Deployment Tool"
requires-python = ">=3.8"
authors = [
    { name = "Chen Wang", email = "wangchen9617@gmail.com"},
]
dependencies = [
    "toml",
    "tomlkit",
    "build",
    "twine",
    "Cython",
    "setuptools>=70",
]

[tool.setuptools]
package-dir = {"" = "src"}
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]

[[tool.bumpversion.file]]
filename = "src/package_deploy/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'